# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85f0b1a591590b9a7ce5199f99dd3050e8b3cd7f17d9abf3eab5cb6ed239eeff64c876c3cbdb69cd8127305205daf7c53283040a02124e4a8b626a929c17404c

test:
  secret_key_base: a48029d396838d8ee0b06164ff1c64a94c3ce532803f481c2073847161c3e9029ca1c6d94a2129d5c13aaf20c4e71890b631a524c7d4856fdd28c0e4022135db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
